spring:
  profiles:
    active: dev
  datasource:
    username: test
    password: 12345678
    url: jdbc:mysql://localhost:3306/furbot?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver

app:
  version: @project.version@
  build:
    time: @build.timestamp@

bot:
  number: 1234567898
  password: 12345678