spring:
  profiles:
    active: dev
  datasource:
    username: test
    password: 12345678
    url: jdbc:mysql://localhost:3306/furbot?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 1000

server:
  port: 23578
  address: 127.0.0.1

app:
  version: @project.version@
  build:
    time: @build.timestamp@

logging:
  level:
    root: info

bot:
  number: 1234567898
  password: 12345678